### ISSUE TITLE
many links of groups are expired

### ISSUE THREAD

**Issue by SinaKarimi7** [ebertti/awesome-telegram#22]
hi, many link you use in this repo is expired or broken. plz update them.

for example:
@awesometelegram – Official group for this awesome list.

**Comment by ebertti** [comment]
Hi,

Not really. 

I'm the admin of this group. It is still working

![image](https://user-images.githubusercontent.com/140394/32984953-3e7f2de0-cc97-11e7-8a15-23d45a157ea3.png)

**Comment by SinaKarimi7** [comment]
no for me it doesn't work:/
